"""Render an ESXi kickstart (ks.cfg) from an InstallSpec.

Every value comes from the validated spec (no free-form input reaches the script), so the output
is safe to embed in shell sections.
"""

from __future__ import annotations

from groundzero.install.spec import InstallSpec

# Persist allowLegacyCPU into the installed system's boot configuration; without it a deprecated
# CPU can stop the installed host from booting. The bootbank mount names differ between installer
# builds, so every boot.cfg reachable under /vmfs/volumes is patched (idempotent).
_PERSIST_LEGACY_CPU = r"""
%post --interpreter=busybox --ignorefailure=true
for cfg in /vmfs/volumes/*/boot.cfg /bootbank/boot.cfg /altbootbank/boot.cfg; do
  [ -f "$cfg" ] || continue
  grep -q 'allowLegacyCPU=true' "$cfg" && continue
  sed -i 's/^kernelopt=\(.*\)$/kernelopt=\1 allowLegacyCPU=true/' "$cfg"
done
"""


def render_kickstart(spec: InstallSpec) -> str:
    net = spec.network
    target = f"--disk={spec.install_disk}" if spec.install_disk else f"--firstdisk={spec.install_firstdisk}"
    install = [f"install {target}"]
    install.append("--preservevmfs" if spec.preserve_vmfs else "--overwritevmfs")
    if spec.allow_legacy_cpu:
        # --forceunsupportedinstall accepts the CPU_SUPPORT OVERRIDEWARNING; without it the 9.1.1
        # installer reports "An error has occurred while parsing the installation script" (live run 8).
        install += ["--forceunsupportedinstall", "--ignoreprereqwarnings", "--ignoreprereqerrors"]

    network = [
        "network --bootproto=static",
        f"--device={net.install_nic}",
        f"--ip={net.ip}",
        f"--netmask={net.netmask}",
        f"--gateway={net.gateway}",
        f"--nameserver={','.join(net.nameservers)}",
        f"--hostname={net.hostname}",
    ]
    if net.vlan_id:
        network.append(f"--vlanid={net.vlan_id}")

    lines = [
        "# Generated by GroundZero. Do not edit by hand; change the InstallSpec instead.",
        "vmaccepteula",
        " ".join(install),
        f"rootpw --iscrypted {spec.root_password_hash}",
        " ".join(network),
        "reboot",
    ]
    script = "\n".join(lines) + "\n"
    if spec.allow_legacy_cpu:
        script += _PERSIST_LEGACY_CPU

    firstboot = []
    for nic in net.extra_uplinks:
        firstboot.append(f"esxcli network vswitch standard uplink add -u {nic} -v vSwitch0")
    if net.extra_uplinks:
        active = ",".join([net.install_nic, *net.extra_uplinks])
        failover = "esxcli network vswitch standard portgroup policy failover set"
        firstboot.append(f'{failover} -p "Management Network" -a {active}')
    if spec.ntp_servers:
        servers = " ".join(f"--server={s}" for s in spec.ntp_servers)
        firstboot.append(f"esxcli system ntp set {servers} --enabled=true")
    if firstboot:
        script += "\n%firstboot --interpreter=busybox\n" + "\n".join(firstboot) + "\n"
    return script
