#!/usr/bin/env python3
"""
Dev-only script: downloads @cds/core/global.min.css from unpkg and embeds it
as a gzip+base64 string constant in groundzero/web/assets.py.

Run once after checkout or whenever Clarity needs updating:
    python tools/bundle_assets.py

No npm, no Node.js required — uses only Python stdlib (urllib, gzip, base64).
"""
import base64
import gzip
import os
import ssl
import sys
import urllib.request

CLARITY_CSS_URL = "https://unpkg.com/@cds/core/global.min.css"
THIS_DIR = os.path.dirname(os.path.abspath(__file__))
OUT_PATH = os.path.join(THIS_DIR, "..", "groundzero", "web", "assets.py")


def _download(url: str) -> bytes:
    ctx = ssl.create_default_context()
    ctx.check_hostname = False
    ctx.verify_mode = ssl.CERT_NONE
    req = urllib.request.Request(url, headers={"User-Agent": "groundzero/bundle"})
    with urllib.request.urlopen(req, context=ctx, timeout=60) as resp:
        return resp.read()


def main():
    print(f"Downloading {CLARITY_CSS_URL} ...")
    try:
        raw = _download(CLARITY_CSS_URL)
    except Exception as exc:
        print(f"ERROR: {exc}", file=sys.stderr)
        sys.exit(1)

    print(f"  Raw size  : {len(raw):>10,} bytes")

    compressed = gzip.compress(raw, compresslevel=9)
    encoded = base64.b64encode(compressed).decode("ascii")

    print(f"  Compressed: {len(compressed):>10,} bytes")
    print(f"  Base64 str: {len(encoded):>10,} chars")

    out_path = os.path.normpath(OUT_PATH)
    os.makedirs(os.path.dirname(out_path), exist_ok=True)

    # Chunk the long string so editors / diffs don't choke on a single 80 KB line
    chunk = 100
    lines = [encoded[i:i+chunk] for i in range(0, len(encoded), chunk)]
    encoded_py = '    "' + '"\n    "'.join(lines) + '"'

    content = f'''\
"""
Auto-generated by tools/bundle_assets.py — do not edit manually.
Refresh with: python tools/bundle_assets.py  (internet access required once)

Third-Party Component:
  VMware Clarity Design System (@cds/core 5.7.0)
  License: Apache License 2.0 (see THIRD_PARTY_LICENSES.md)
  Copyright (c) 2016-2024 VMware, Inc. All Rights Reserved.

Embeds @cds/core/global.min.css as gzip+base64:
  Raw : {len(raw):,} bytes
  Compressed : {len(compressed):,} bytes
"""
# fmt: off
CLARITY_CSS_GZ_B64: str = (
{encoded_py}
)
# fmt: on
'''

    with open(out_path, "w", encoding="utf-8") as fh:
        fh.write(content)

    print(f"Written → {os.path.relpath(out_path)}")


if __name__ == "__main__":
    main()
